INSERT INTO  products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Bagla Mukhi Yantra',
    'bagla-mukhi-yantra',
    '24K Gold Plated',
    'Yantra',
    'Protection',
    59900,
    89900,
    4.8,
    312,
    'https://washi-custom-22412387.figma.site/_components/v2/0efc643709f6f883f69747b3c071474ddf94fb96/WhatsApp_Image_2026-07-04_at_20.51.30.b3cad81a.jpeg',
    '["Temple Energized","Bestseller"]',
    'Stambhan · Vijay · Raksha. Controls negativity, brings victory in legal matters and protects from enemies.',
    '["Victory in Legal Matters","Protection From Enemies","Increases Confidence","Improves Communication","Brings Peace & Mental Stability"]',
    '3.5 cm x 3.5 cm (Approx.)',
    'Metal (Golden Finish)',
    '["Pendant","Pocket","Wallet","Car","Pooja Sthal","Safe/Locker"]',
    'Shri Bagla Mukhi Yantra. Stambhan Shakti. Vijay & Protection. Enhances Will Power. Brings Control Over Negativity & Enemies. Divine Golden Finish. Perfect for Daily Carry.',
    100
  );
INSERT INTO  products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Nepal Origin 1 Mukhi Rudraksha - 17mm to 22mm (Kaju Shape)',
    'nepal-origin-1-mukhi-rudraksha-17mm-to-22mm-kaju-shape',
    'Authentic & Energized',
    'Rudraksha',
    'Well-being',
    790900,
    949080,
    4.6,
    472,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/1_a144e37f-680e-430f-80bd-e7c35b9d2ebb.webp?v=1759924225',
    '["Authentic","Energized"]',
    'The Natural Kaju Shape Ek Mukhi Rudraksha , especially the rare Nepal origin bead, represents Lord S...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'The Natural Kaju Shape Ek Mukhi Rudraksha , especially the rare Nepal origin bead, represents Lord Shiva in his purest form. It enhances focus, peace, and spiritual awakening, helping remove negative energies and deepen meditation. Ideal for seekers of strength, clarity, and divine connection on the path to moksha (liberation). These Nepali 1 Mukhi Rudraksha are rare, balanced, and spiritually powerful , while a fully developed single-seed round bead is almost impossible to find. You can gift this Rudraksha to your family and friends, including women and children, to bring calm, strength, and good energy. It is a perfect gift when you want to bless someone with protection, peace, and positive vibes.',
    50
  );
INSERT INTO  products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Citrine Sun Ring',
    'citrine-sun-ring',
    'Authentic & Energized',
    'Puja Items',
    'Well-being',
    69900,
    83880,
    4.6,
    96,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/Artboard1_19.webp?v=1782733204',
    '["Authentic","Energized"]',
    'This beautiful ring is crafted with natural Citrine , known for attracting wealth, positivity, and s...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'This beautiful ring is crafted with natural Citrine , known for attracting wealth, positivity, and success, paired with the powerful Sun symbol connected to Surya Dev. As 2026 is ruled by the Sun , this ring represents confidence, abundance, growth, and powerful new beginnings. Key Benefits: Attracts Abundance - Citrine invites wealth and removes money blocks Boosts Confidence - Helps you feel bold and think clearly Lifts Your Mood - Brings positivity and reduces overthinking Connects to Surya - Strengthens solar energy and personal power Adjustable and crafted from premium brass, this ring fits comfortably for daily wear and makes a meaningful gift.',
    50
  );
INSERT INTO  products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Pyrite Sun Ring',
    'pyrite-sun-ring',
    'Authentic & Energized',
    'Puja Items',
    'Well-being',
    69900,
    83880,
    4.9,
    100,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/Artboard1_18.webp?v=1782199970',
    '["Authentic","Energized"]',
    'This ring combines the powerful Sun symbol of Surya Dev with wealth-attracting Raw Pyrite, making it...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'This ring combines the powerful Sun symbol of Surya Dev with wealth-attracting Raw Pyrite, making it especially meaningful for 2026, the “Year of Surya.” As the year is ruled by the Sun, wearing this ring is believed to support financial growth, success , and positive new beginnings . Key Benefits: Attracts Wealth - Pyrite draws in money, energy, and opens new income doors Boosts Confidence - Surya''s power helps you speak up and stand strong Brings Mental Clarity - Clears confusion so you can decide with a calm mind Shields from Negativity - Protects you from buri nazar and bad energy Adjustable and made with premium brass metal, this ring fits comfortably for daily wear and makes a meaningful gift.',
    50
  );
INSERT INTO  products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Love & Money Metal Bracelet for Women',
    'love-money-metal-bracelet-for-women',
    'Authentic & Energized',
    'Puja Items',
    'Well-being',
    99900,
    119880,
    4.8,
    298,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/1_23.jpg?v=1782120393',
    '["Authentic","Energized"]',
    'This bracelet combines Pyrite and Garnet stones to attract money and bring love into your life. It h...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'This bracelet combines Pyrite and Garnet stones to attract money and bring love into your life. It helps you feel confident, emotionally balanced, and open to better opportunities. Key Benefits: • Attracts Money - Pyrite invites new income and removes financial blockages • Brings Love - Garnet supports love, commitment, and emotional harmony • Builds Confidence - Helps you feel worthy and take bold decisions • Protects Your Energy - Guards against buri nazar and negative energy Made with a durable brass base and premium IGP plating for a long-lasting shine. It is perfect for everyday wear and makes a meaningful gift for yourself or your loved ones.',
    50
  );
INSERT INTO  products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Dhan Yog Necklace',
    'dhan-yog-necklace',
    'Authentic & Energized',
    'Puja Items',
    'Well-being',
    99900,
    119880,
    4.7,
    519,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/1-2026-06-19T175355.300.webp?v=1781871863',
    '["Authentic","Energized"]',
    'The Dhan Yog Necklace is designed to attract wealth, abundance, and good fortune while adding a time...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'The Dhan Yog Necklace is designed to attract wealth, abundance, and good fortune while adding a timeless and elegant touch to your everyday style. Crafted with powerful crystals like: • Pyrite – Attracts Wealth • Citrine – Boosts Abundance • Quartz – Amplifies Crystal Energy • Green Aventurine – Brings Luck • Tiger Eye – Builds Confidence Made with a durable brass base and premium IGP plating for a long-lasting shine. It is also perfect for everyday wear and makes a meaningful gift for yourself or your loved ones.',
    50
  );
INSERT INTO  products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Kirtimukha - Prosperity & Protection Kavach',
    'kirtimukha-prosperity-protection-kavach',
    'Authentic & Energized',
    'Puja Items',
    'Well-being',
    99900,
    119880,
    4.6,
    147,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/1-1_f53e2d9e-40a0-4f0e-95a9-8d6a878b2f77.webp?v=1781163169',
    '["Authentic","Energized"]',
    'Bring home the Kirtimukha made with Black Tourmaline and invite the blessings of Lord Shiva''s divine...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'Bring home the Kirtimukha made with Black Tourmaline and invite the blessings of Lord Shiva''s divine protection into your space. Born from Shiva''s third eye , it is a powerful guardian against Rahu energies, buri nazar, and all forms of negativity. Key Benefits • Blocks Negativity - Placed at the entrance, it stops heavy and shadow energies before they enter. • Rahu Shanti - Helps reduce confusion, fear, and mental heaviness linked to Rahu''s influence. • Triple Protection - Features Ganesha for obstacle removal, Adi Shesha for divine protection, and Black Tourmaline for grounding energy. • Sacred Vastu Symbol - Removes ego, greed &amp; bad energies to create a protected, positive space. A meaningful gift for new homes, temple spaces &amp; spiritual housewarmings. Place above doors, temples, or office entrances.',
    50
  );
INSERT INTO  products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Tiger Eye Sun Ring',
    'tiger-eye-sun-ring',
    'Authentic & Energized',
    'Puja Items',
    'Well-being',
    69900,
    83880,
    4.6,
    332,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/Artboard1_17.webp?v=1781609564',
    '["Authentic","Energized"]',
    'This powerful ring is crafted with natural Tiger Eye , a stone known for confidence, protection, foc...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'This powerful ring is crafted with natural Tiger Eye , a stone known for confidence, protection, focus, and courage, paired with the sacred Sun symbol connected to Surya Dev. As 2026 is ruled by the Sun , this ring represents strength, leadership, clarity, and powerful personal growth. Key Benefits: • Boosts Confidence - Helps you feel fearless, bold, and mentally strong • Protects From Negativity - Shields against buri nazar and negative energies • Improves Focus - Keeps your thoughts clear and supports better decision-making • Connects to Surya - Strengthens personal power, courage, and leadership energy Adjustable and crafted from premium brass, this ring fits comfortably for daily wear and makes a meaningful gift.',
    50
  );
INSERT INTO  products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Nepal Origin 5 Mukhi Rudraksha Bead - 8mm to 12mm (FREE GIFT)',
    'nepal-origin-5-mukhi-rudraksha-bead-8mm-to-12mm-free-gift',
    'Authentic & Energized',
    'Rudraksha',
    'Well-being',
    100,
    120,
    4.9,
    89,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/1_6.webp?v=1751001522',
    '["Authentic","Energized"]',
    'The Nepal Origin 5 Mukhi Rudraksha , especially the original 5 Mukhi Rudraksha, is one of the most w...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'The Nepal Origin 5 Mukhi Rudraksha , especially the original 5 Mukhi Rudraksha, is one of the most widely revered and spiritually potent Rudraksha beads. Blessed by Lord Shiva, it symbolizes the five elements and channels his divine energy. Among the powerful 5 Mukhi Rudraksha benefits are enhanced mental clarity, emotional balance and reduced stress. Ideal for meditation and daily wear, this sacred bead promotes inner peace, spiritual growth, and protection from negativity, making it a must-have for seekers of balance and well-being. You can gift this Rudraksha to your family and friends, including women and children, to bring calm, strength, and good energy. It is a perfect gift when you want to bless someone with protection, peace, and positive vibes.',
    50
  );
INSERT INTO  products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Pearl',
    'pearl',
    'Authentic & Energized',
    'Puja Items',
    'Well-being',
    385400,
    462480,
    4.6,
    259,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/South-Sea-Pearl_1.webp?v=1771406188',
    '["Authentic","Energized"]',
    'Pearl (Moti) is a soothing gemstone known for bringing peace and calm to the mind. It helps reduce s...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'Pearl (Moti) is a soothing gemstone known for bringing peace and calm to the mind. It helps reduce stress and anxiety while promoting emotional balance. Our natural, certified pearls are carefully selected for their beautiful luster and purity. Pearl is usually worn in Gold, Silver, or Panchdhatu rings or pendants. Panchdhatu metal can lose color with frequent contact with water, sweat, or perfume. Keep the ring dry to maintain its shine for a longer time.',
    50
  );
