
ALTER TABLE products ADD COLUMN IF NOT EXISTS slug text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS subtitle text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS category text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS purpose text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS original_price bigint;
ALTER TABLE products ADD COLUMN IF NOT EXISTS rating numeric;
ALTER TABLE products ADD COLUMN IF NOT EXISTS reviews int;
ALTER TABLE products ADD COLUMN IF NOT EXISTS img text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS badges jsonb;
ALTER TABLE products ADD COLUMN IF NOT EXISTS short_desc text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS benefits jsonb;
ALTER TABLE products ADD COLUMN IF NOT EXISTS size text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS material text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS use_for jsonb;

DELETE FROM order_items;
DELETE FROM cart_items;
DELETE FROM products;

INSERT INTO products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Bagla Mukhi Yantra',
    'bagla-mukhi-yantra',
    '24K Gold Plated',
    'Yantra',
    'Protection',
    59900,
    89900,
    4.8,
    312,
    'https://washi-custom-22412387.figma.site/_components/v2/0efc643709f6f883f69747b3c071474ddf94fb96/WhatsApp_Image_2026-07-04_at_20.51.30.b3cad81a.jpeg',
    '["Temple Energized","Bestseller"]',
    'Stambhan · Vijay · Raksha. Controls negativity, brings victory in legal matters and protects from enemies.',
    '["Victory in Legal Matters","Protection From Enemies","Increases Confidence","Improves Communication","Brings Peace & Mental Stability"]',
    '3.5 cm x 3.5 cm (Approx.)',
    'Metal (Golden Finish)',
    '["Pendant","Pocket","Wallet","Car","Pooja Sthal","Safe/Locker"]',
    'Shri Bagla Mukhi Yantra. Stambhan Shakti. Vijay & Protection. Enhances Will Power. Brings Control Over Negativity & Enemies. Divine Golden Finish. Perfect for Daily Carry.',
    100
  );
INSERT INTO products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Nepal Origin 1 Mukhi Rudraksha - 17mm to 22mm (Kaju Shape)',
    'nepal-origin-1-mukhi-rudraksha-17mm-to-22mm-kaju-shape',
    'Authentic & Energized',
    'Rudraksha',
    'Well-being',
    790900,
    949080,
    4.6,
    472,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/1_a144e37f-680e-430f-80bd-e7c35b9d2ebb.webp?v=1759924225',
    '["Authentic","Energized"]',
    'The Natural Kaju Shape Ek Mukhi Rudraksha , especially the rare Nepal origin bead, represents Lord S...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'The Natural Kaju Shape Ek Mukhi Rudraksha , especially the rare Nepal origin bead, represents Lord Shiva in his purest form. It enhances focus, peace, and spiritual awakening, helping remove negative energies and deepen meditation. Ideal for seekers of strength, clarity, and divine connection on the path to moksha (liberation). These Nepali 1 Mukhi Rudraksha are rare, balanced, and spiritually powerful , while a fully developed single-seed round bead is almost impossible to find. You can gift this Rudraksha to your family and friends, including women and children, to bring calm, strength, and good energy. It is a perfect gift when you want to bless someone with protection, peace, and positive vibes.',
    50
  );
INSERT INTO products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Citrine Sun Ring',
    'citrine-sun-ring',
    'Authentic & Energized',
    'Puja Items',
    'Well-being',
    69900,
    83880,
    4.6,
    96,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/Artboard1_19.webp?v=1782733204',
    '["Authentic","Energized"]',
    'This beautiful ring is crafted with natural Citrine , known for attracting wealth, positivity, and s...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'This beautiful ring is crafted with natural Citrine , known for attracting wealth, positivity, and success, paired with the powerful Sun symbol connected to Surya Dev. As 2026 is ruled by the Sun , this ring represents confidence, abundance, growth, and powerful new beginnings. Key Benefits: Attracts Abundance - Citrine invites wealth and removes money blocks Boosts Confidence - Helps you feel bold and think clearly Lifts Your Mood - Brings positivity and reduces overthinking Connects to Surya - Strengthens solar energy and personal power Adjustable and crafted from premium brass, this ring fits comfortably for daily wear and makes a meaningful gift.',
    50
  );
INSERT INTO products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Pyrite Sun Ring',
    'pyrite-sun-ring',
    'Authentic & Energized',
    'Puja Items',
    'Well-being',
    69900,
    83880,
    4.9,
    100,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/Artboard1_18.webp?v=1782199970',
    '["Authentic","Energized"]',
    'This ring combines the powerful Sun symbol of Surya Dev with wealth-attracting Raw Pyrite, making it...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'This ring combines the powerful Sun symbol of Surya Dev with wealth-attracting Raw Pyrite, making it especially meaningful for 2026, the “Year of Surya.” As the year is ruled by the Sun, wearing this ring is believed to support financial growth, success , and positive new beginnings . Key Benefits: Attracts Wealth - Pyrite draws in money, energy, and opens new income doors Boosts Confidence - Surya''s power helps you speak up and stand strong Brings Mental Clarity - Clears confusion so you can decide with a calm mind Shields from Negativity - Protects you from buri nazar and bad energy Adjustable and made with premium brass metal, this ring fits comfortably for daily wear and makes a meaningful gift.',
    50
  );
INSERT INTO products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Love & Money Metal Bracelet for Women',
    'love-money-metal-bracelet-for-women',
    'Authentic & Energized',
    'Puja Items',
    'Well-being',
    99900,
    119880,
    4.8,
    298,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/1_23.jpg?v=1782120393',
    '["Authentic","Energized"]',
    'This bracelet combines Pyrite and Garnet stones to attract money and bring love into your life. It h...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'This bracelet combines Pyrite and Garnet stones to attract money and bring love into your life. It helps you feel confident, emotionally balanced, and open to better opportunities. Key Benefits: • Attracts Money - Pyrite invites new income and removes financial blockages • Brings Love - Garnet supports love, commitment, and emotional harmony • Builds Confidence - Helps you feel worthy and take bold decisions • Protects Your Energy - Guards against buri nazar and negative energy Made with a durable brass base and premium IGP plating for a long-lasting shine. It is perfect for everyday wear and makes a meaningful gift for yourself or your loved ones.',
    50
  );
INSERT INTO products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Dhan Yog Necklace',
    'dhan-yog-necklace',
    'Authentic & Energized',
    'Puja Items',
    'Well-being',
    99900,
    119880,
    4.7,
    519,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/1-2026-06-19T175355.300.webp?v=1781871863',
    '["Authentic","Energized"]',
    'The Dhan Yog Necklace is designed to attract wealth, abundance, and good fortune while adding a time...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'The Dhan Yog Necklace is designed to attract wealth, abundance, and good fortune while adding a timeless and elegant touch to your everyday style. Crafted with powerful crystals like: • Pyrite – Attracts Wealth • Citrine – Boosts Abundance • Quartz – Amplifies Crystal Energy • Green Aventurine – Brings Luck • Tiger Eye – Builds Confidence Made with a durable brass base and premium IGP plating for a long-lasting shine. It is also perfect for everyday wear and makes a meaningful gift for yourself or your loved ones.',
    50
  );
INSERT INTO products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Kirtimukha - Prosperity & Protection Kavach',
    'kirtimukha-prosperity-protection-kavach',
    'Authentic & Energized',
    'Puja Items',
    'Well-being',
    99900,
    119880,
    4.6,
    147,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/1-1_f53e2d9e-40a0-4f0e-95a9-8d6a878b2f77.webp?v=1781163169',
    '["Authentic","Energized"]',
    'Bring home the Kirtimukha made with Black Tourmaline and invite the blessings of Lord Shiva''s divine...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'Bring home the Kirtimukha made with Black Tourmaline and invite the blessings of Lord Shiva''s divine protection into your space. Born from Shiva''s third eye , it is a powerful guardian against Rahu energies, buri nazar, and all forms of negativity. Key Benefits • Blocks Negativity - Placed at the entrance, it stops heavy and shadow energies before they enter. • Rahu Shanti - Helps reduce confusion, fear, and mental heaviness linked to Rahu''s influence. • Triple Protection - Features Ganesha for obstacle removal, Adi Shesha for divine protection, and Black Tourmaline for grounding energy. • Sacred Vastu Symbol - Removes ego, greed &amp; bad energies to create a protected, positive space. A meaningful gift for new homes, temple spaces &amp; spiritual housewarmings. Place above doors, temples, or office entrances.',
    50
  );
INSERT INTO products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Tiger Eye Sun Ring',
    'tiger-eye-sun-ring',
    'Authentic & Energized',
    'Puja Items',
    'Well-being',
    69900,
    83880,
    4.6,
    332,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/Artboard1_17.webp?v=1781609564',
    '["Authentic","Energized"]',
    'This powerful ring is crafted with natural Tiger Eye , a stone known for confidence, protection, foc...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'This powerful ring is crafted with natural Tiger Eye , a stone known for confidence, protection, focus, and courage, paired with the sacred Sun symbol connected to Surya Dev. As 2026 is ruled by the Sun , this ring represents strength, leadership, clarity, and powerful personal growth. Key Benefits: • Boosts Confidence - Helps you feel fearless, bold, and mentally strong • Protects From Negativity - Shields against buri nazar and negative energies • Improves Focus - Keeps your thoughts clear and supports better decision-making • Connects to Surya - Strengthens personal power, courage, and leadership energy Adjustable and crafted from premium brass, this ring fits comfortably for daily wear and makes a meaningful gift.',
    50
  );
INSERT INTO products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Nepal Origin 5 Mukhi Rudraksha Bead - 8mm to 12mm (FREE GIFT)',
    'nepal-origin-5-mukhi-rudraksha-bead-8mm-to-12mm-free-gift',
    'Authentic & Energized',
    'Rudraksha',
    'Well-being',
    100,
    120,
    4.9,
    89,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/1_6.webp?v=1751001522',
    '["Authentic","Energized"]',
    'The Nepal Origin 5 Mukhi Rudraksha , especially the original 5 Mukhi Rudraksha, is one of the most w...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'The Nepal Origin 5 Mukhi Rudraksha , especially the original 5 Mukhi Rudraksha, is one of the most widely revered and spiritually potent Rudraksha beads. Blessed by Lord Shiva, it symbolizes the five elements and channels his divine energy. Among the powerful 5 Mukhi Rudraksha benefits are enhanced mental clarity, emotional balance and reduced stress. Ideal for meditation and daily wear, this sacred bead promotes inner peace, spiritual growth, and protection from negativity, making it a must-have for seekers of balance and well-being. You can gift this Rudraksha to your family and friends, including women and children, to bring calm, strength, and good energy. It is a perfect gift when you want to bless someone with protection, peace, and positive vibes.',
    50
  );
INSERT INTO products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Pearl',
    'pearl',
    'Authentic & Energized',
    'Puja Items',
    'Well-being',
    385400,
    462480,
    4.6,
    259,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/South-Sea-Pearl_1.webp?v=1771406188',
    '["Authentic","Energized"]',
    'Pearl (Moti) is a soothing gemstone known for bringing peace and calm to the mind. It helps reduce s...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'Pearl (Moti) is a soothing gemstone known for bringing peace and calm to the mind. It helps reduce stress and anxiety while promoting emotional balance. Our natural, certified pearls are carefully selected for their beautiful luster and purity. Pearl is usually worn in Gold, Silver, or Panchdhatu rings or pendants. Panchdhatu metal can lose color with frequent contact with water, sweat, or perfume. Keep the ring dry to maintain its shine for a longer time.',
    50
  );
INSERT INTO products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Collector''s Edition 5 Mukhi Rudraksha (Nepali Origin)',
    'collector-s-edition-5-mukhi-rudraksha-nepali-origin',
    'Authentic & Energized',
    'Rudraksha',
    'Well-being',
    99900,
    119880,
    4.9,
    303,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/Artboard1_15.webp?v=1780903458',
    '["Authentic","Energized"]',
    '5 Mukhi Rudraksha , also known as panchmukhi rudraksha, is a sacred bead blessed by Lord Shiva, know...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    '5 Mukhi Rudraksha , also known as panchmukhi rudraksha, is a sacred bead blessed by Lord Shiva, known for protection and spiritual growth. Spiritual Significance &amp; Key Details: • Ruling Planet : Jupiter (Guru), which boosts wisdom and improves decision-making • Ruling Deity : Lord Kalagni Rudra (Shiva), who brings protection and inner strength • Represents : Five elements that balance mind, body, and energy • Suitable Rashi: All Zodiac Signs • Ideal For : Daily wear, meditation, and stress relief Perfect meaningful spiritual gift for your loved ones who constantly face stress or negativity.',
    50
  );
INSERT INTO products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    '7 Horses Karungali Mala',
    '7-horses-karungali-mala',
    'Authentic & Energized',
    'Puja Items',
    'Well-being',
    99900,
    119880,
    4.5,
    74,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/1-2026-06-03T160348.499.webp?v=1780482936',
    '["Authentic","Energized"]',
    'This powerful mala combines the sacred 7 Horses brass pendant with protective Karungali beads , maki...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'This powerful mala combines the sacred 7 Horses brass pendant with protective Karungali beads , making it especially meaningful for 2026 . As this year is ruled by the Sun , wearing this mala symbolises success , growth , confidence , and strong forward movement in life. Key Benefits: • Attracts Success &amp; Growth - The 7 Horses symbol represents victory, progress &amp; achievement • Brings Financial Stability – Helps attract abundance &amp; remove financial blockages • Boosts Confidence &amp; Courage – Surya energy supports leadership &amp; self-belief • Protects From Negativity - Karungali helps shield from buri nazar &amp; negative energies Strong, spiritual, and easy to wear daily, this mala makes a meaningful addition to your spiritual journey.',
    50
  );
INSERT INTO products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Dhan Yog Prosperity Set for Women',
    'dhan-yog-prosperity-set-for-women',
    'Authentic & Energized',
    'Puja Items',
    'Well-being',
    129900,
    155880,
    5.0,
    383,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/Artboard1_12_1.webp?v=1780380318',
    '["Authentic","Energized"]',
    'Made for women who want to attract wealth, success, and positive energy, this set helps boost confid...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'Made for women who want to attract wealth, success, and positive energy, this set helps boost confidence, improve focus, and support personal growth. What’s Inside • Dhan Yog Bracelet for Women – Crafted with Pyrite, Citrine, Quartz, Green Aventurine, and Tiger Eye to support wealth attraction, career growth, confidence, luck, and positive energy. • Dhan Yog Anklet – Crafted with Pyrite, Citrine, Green Aventurine, Tiger Eye, Black Obsidian, and Garnet to support financial progress, confidence, protection from negativity, emotional balance, and new opportunities. A meaningful gift for wives, sisters, mothers, daughters, or any woman looking to attract prosperity, confidence, and success in life.',
    50
  );
INSERT INTO products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Metal Dhan Yog Bracelet for Women with FREE Raw Pyrite Anklet',
    'metal-dhan-yog-bracelet-for-women-with-free-raw-pyrite-anklet',
    'Authentic & Energized',
    'Puja Items',
    'Well-being',
    129900,
    155880,
    4.8,
    78,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/Artboard_1_16.webp?v=1780911809',
    '["Authentic","Energized"]',
    'This wealth-attracting combo pairs a Pyrite, Citrine, Quartz, Green Aventurine, and Tiger Eye bracel...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'This wealth-attracting combo pairs a Pyrite, Citrine, Quartz, Green Aventurine, and Tiger Eye bracelet with a Raw Pyrite Anklet to invite money and confidence together. It helps you feel grounded, focused, and ready to grow. Key Benefits: • Attracts Wealth - Pyrite and Citrine together support money flow and career growth • Boosts Confidence - Tiger Eye strengthens your belief in yourself and your decisions • Amplifies Energy - Quartz multiplies the power of every crystal in this combo • Brings Luck - Green Aventurine opens doors to new opportunities and positive shifts Lightweight and elegant on the wrist and ankle, this combo also makes a meaningful gift for someone ready to grow.',
    50
  );
INSERT INTO products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Karungali Malai Silver Capped  6mm – 54+1 Beads (Govt. Certified)',
    'karungali-malai-silver-capped-6mm-54-1-beads-govt-certified',
    'Authentic & Energized',
    'Puja Items',
    'Well-being',
    79900,
    95880,
    4.5,
    184,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/1_11_19940cf3-8b42-403e-a8fd-9a46cd8161bb.webp?v=1780318572',
    '["Authentic","Energized"]',
    'This sacred Karungali Mala is made from pure Black Ebony Wood with silver caps on each of the 54+1 b...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'This sacred Karungali Mala is made from pure Black Ebony Wood with silver caps on each of the 54+1 beads. Wearing it daily helps you feel protected, spiritually grounded, and connected to Lord Murugan''s blessings . Key Benefits: Removes Negativity - Karungali wood absorbs negative energy and shields your aura Deepens Meditation - 54+1 bead count supports focused japam and daily chanting Brings Mental Clarity - Silver caps cool the mind and improve concentration Strengthens Faith - Connects you to divine protection and higher spiritual guidance Each mala is crafted with anti-tarnish oxidised silver-plated caps, and also makes it a meaningful gift for any devotee.',
    50
  );
INSERT INTO products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Grah Shanti Yantra with Black Tourmaline Frame',
    'grah-shanti-yantra-with-black-tourmaline-frame',
    'Authentic & Energized',
    'Puja Items',
    'Well-being',
    99900,
    119880,
    4.9,
    543,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/Artboard_1_4_d1608791-8b80-4714-aec9-07df075c45a3.webp?v=1779858927',
    '["Authentic","Energized"]',
    'Bring peace, protection, and positive energy into your space with the Grah Shanti Yantra Frame with ...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'Bring peace, protection, and positive energy into your space with the Grah Shanti Yantra Frame with Black Tourmaline . Inspired by Vedic Astrology, this sacred yantra features a Mangal Grah (Mars) grid , where every direction adds up to 9 , symbolising strength, stability, and protection. Key Benefits: Mangal Yantra Energy – Helps reduce stress, conflicts, anger, and marriage-related issues while promoting harmony and balance. Sacred Mantras – Engraved with spiritual mantras to attract peaceful, protective vibrations. Black Tourmaline – Absorb negativity, protect from buri nazar, and create a positive atmosphere. Ideal for your living room, home entrance area, or meditation space .',
    50
  );
INSERT INTO products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Divya Raksha Mala With 5 Mukhi Trishul Pendant',
    'divya-raksha-mala-with-5-mukhi-trishul-pendant',
    'Authentic & Energized',
    'Puja Items',
    'Well-being',
    99900,
    119880,
    4.8,
    290,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/Artboard1_9_1.webp?v=1779425457',
    '["Authentic","Energized"]',
    'This sacred mala combines Karungali wood beads, Rudraksha, and 5 Mukhi Rudraksha with a Trishul pend...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'This sacred mala combines Karungali wood beads, Rudraksha, and 5 Mukhi Rudraksha with a Trishul pendant, inspired by the divine energies of Lord Shiva &amp; Lord Murugan . Key Benefits: • Spiritual Protection - Karungali and Rudraksha together shield from buri nazar and negative energy. • Mental Clarity - The 5 Mukhi Trishul pendant calms the mind and sharpens focus. • Inner Strength - Lord Shiva’s Trishul awakens courage and personal power. • Removes Obstacles - Clears blockages in your path and invites positive energy. Designed for daily wear, it features anti-tarnish oxidised silver plating and a brass Trishul pendant with long-lasting shine and durability.',
    50
  );
INSERT INTO products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Karungali Murugan Raksha Mala',
    'karungali-murugan-raksha-mala',
    'Authentic & Energized',
    'Puja Items',
    'Well-being',
    99900,
    119880,
    4.5,
    413,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/Gemini_Generated_Image_v3lcuev3lcuev3lc_1.webp?v=1779692958',
    '["Authentic","Energized"]',
    'Karungali Murugan Raksha Mala brings the divine blessings of Lord Murugan with the sacred energy of ...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'Karungali Murugan Raksha Mala brings the divine blessings of Lord Murugan with the sacred energy of Karungali wood. Sacred Elements in This Mala: • 54 Karungali Beads : Help absorb negativity and maintain positive energy throughout the day • Murugan Pendant : Symbolises courage, divine guidance, and victory over obstacles • Large 17 mm Centre Bead – Represents grounding, stability, focus, and a strong spiritual presence. Designed with an oxidised silver-finish brass pendant and silver-plated caps, this mala offers a bold spiritual look and makes a meaningful gift for protection, blessings, and positivity.',
    50
  );
INSERT INTO products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Metal Dhan Yog Couple Bracelet Combo',
    'metal-dhan-yog-couple-bracelet-combo',
    'Authentic & Energized',
    'Puja Items',
    'Well-being',
    159900,
    191880,
    4.7,
    394,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/Artboard_1_10.webp?v=1779448821',
    '["Authentic","Energized"]',
    'Made for couples working hard to build a better future together, this combo supports money growth, c...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'Made for couples working hard to build a better future together, this combo supports money growth, career progress, confidence, and financial stability. What’s Inside • Metal Dhan Yog Bracelet for Men (Silver) – Made with Pyrite, Citrine, Tiger Eye, Green Aventurine, and Quartz to support wealth attraction, business growth, leadership qualities, and strong decision-making. • Metal Dhan Yog Bracelet for Women – Made with Pyrite, Citrine, Tiger Eye, Green Aventurine, and Quartz to support financial positivity, emotional balance, self-belief, and new opportunities. Crafted with premium anti-tarnish silver plating, this meaningful couple combo also makes a thoughtful gift for weddings, anniversaries, and partners building a stable life together.',
    50
  );
INSERT INTO products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Dhan Labh Tortoise',
    'dhan-labh-tortoise',
    'Authentic & Energized',
    'Puja Items',
    'Well-being',
    99900,
    119880,
    4.8,
    56,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/Artboard1_9.webp?v=1779101616',
    '["Authentic","Energized"]',
    'In Vastu Shastra , the tortoise symbolises Lord Kurma, representing stability and protection. Crafte...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'In Vastu Shastra , the tortoise symbolises Lord Kurma, representing stability and protection. Crafted with Pyrite for wealth, and Citrine crystals placed on the tortoise’s back represent prosperity, the Dhan Labh Tortoise symbolises abundance, positivity, and financial growth. Vastu Benefits Attracts Wealth - Place it in the North to invite steady income and financial growth. Eases Financial Stress - Brings stability, calm, and reassurance during difficult financial phases. Boosts Business &amp; Career - Supports growth, new opportunities, and professional success. Perfect Vastu Gift - A deeply meaningful gift for new homes, businesses, and prosperity wishes. Ideal for home, office, shop, cash counter &amp; people seeking dhan labh and financial growth.',
    50
  );
INSERT INTO products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Khatu Shyam Murti with Dome',
    'khatu-shyam-murti-with-dome',
    'Authentic & Energized',
    'Puja Items',
    'Well-being',
    119900,
    143880,
    4.7,
    477,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/1-2026-05-18T155529.062.webp?v=1779099953',
    '["Authentic","Energized"]',
    'Bring home the divine blessing of Shyam Baba into your home with the Khatu Shyam Murti with Dome - a...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'Bring home the divine blessing of Shyam Baba into your home with the Khatu Shyam Murti with Dome - a sacred idol that brings devotion, hope, prosperity and divine protection to your space. Khatu Shyam ji is lovingly called "Hare Ka Sahara" - the one who holds the hand of those who have lost all hope. Key Benefits Divine Protection - Keeps your home and family safe from buri nazar and negative energy. Peace and Positivity - Fills your space with calm and devotion every single day. Hope and New Beginnings - Invites Shyam Baba''s grace during difficult times and struggles. Perfect Gift - A heartfelt gift for housewarming, weddings, and blessings. Ideal for home mandir, office, and car dashboard.',
    50
  );
