INSERT INTO  products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Collector''s Edition 5 Mukhi Rudraksha (Nepali Origin)',
    'collector-s-edition-5-mukhi-rudraksha-nepali-origin',
    'Authentic & Energized',
    'Rudraksha',
    'Well-being',
    99900,
    119880,
    4.9,
    303,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/Artboard1_15.webp?v=1780903458',
    '["Authentic","Energized"]',
    '5 Mukhi Rudraksha , also known as panchmukhi rudraksha, is a sacred bead blessed by Lord Shiva, know...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    '5 Mukhi Rudraksha , also known as panchmukhi rudraksha, is a sacred bead blessed by Lord Shiva, known for protection and spiritual growth. Spiritual Significance &amp; Key Details: • Ruling Planet : Jupiter (Guru), which boosts wisdom and improves decision-making • Ruling Deity : Lord Kalagni Rudra (Shiva), who brings protection and inner strength • Represents : Five elements that balance mind, body, and energy • Suitable Rashi: All Zodiac Signs • Ideal For : Daily wear, meditation, and stress relief Perfect meaningful spiritual gift for your loved ones who constantly face stress or negativity.',
    50
  );
INSERT INTO  products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    '7 Horses Karungali Mala',
    '7-horses-karungali-mala',
    'Authentic & Energized',
    'Puja Items',
    'Well-being',
    99900,
    119880,
    4.5,
    74,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/1-2026-06-03T160348.499.webp?v=1780482936',
    '["Authentic","Energized"]',
    'This powerful mala combines the sacred 7 Horses brass pendant with protective Karungali beads , maki...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'This powerful mala combines the sacred 7 Horses brass pendant with protective Karungali beads , making it especially meaningful for 2026 . As this year is ruled by the Sun , wearing this mala symbolises success , growth , confidence , and strong forward movement in life. Key Benefits: • Attracts Success &amp; Growth - The 7 Horses symbol represents victory, progress &amp; achievement • Brings Financial Stability – Helps attract abundance &amp; remove financial blockages • Boosts Confidence &amp; Courage – Surya energy supports leadership &amp; self-belief • Protects From Negativity - Karungali helps shield from buri nazar &amp; negative energies Strong, spiritual, and easy to wear daily, this mala makes a meaningful addition to your spiritual journey.',
    50
  );
INSERT INTO  products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Dhan Yog Prosperity Set for Women',
    'dhan-yog-prosperity-set-for-women',
    'Authentic & Energized',
    'Puja Items',
    'Well-being',
    129900,
    155880,
    5.0,
    383,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/Artboard1_12_1.webp?v=1780380318',
    '["Authentic","Energized"]',
    'Made for women who want to attract wealth, success, and positive energy, this set helps boost confid...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'Made for women who want to attract wealth, success, and positive energy, this set helps boost confidence, improve focus, and support personal growth. What’s Inside • Dhan Yog Bracelet for Women – Crafted with Pyrite, Citrine, Quartz, Green Aventurine, and Tiger Eye to support wealth attraction, career growth, confidence, luck, and positive energy. • Dhan Yog Anklet – Crafted with Pyrite, Citrine, Green Aventurine, Tiger Eye, Black Obsidian, and Garnet to support financial progress, confidence, protection from negativity, emotional balance, and new opportunities. A meaningful gift for wives, sisters, mothers, daughters, or any woman looking to attract prosperity, confidence, and success in life.',
    50
  );
INSERT INTO  products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Metal Dhan Yog Bracelet for Women with FREE Raw Pyrite Anklet',
    'metal-dhan-yog-bracelet-for-women-with-free-raw-pyrite-anklet',
    'Authentic & Energized',
    'Puja Items',
    'Well-being',
    129900,
    155880,
    4.8,
    78,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/Artboard_1_16.webp?v=1780911809',
    '["Authentic","Energized"]',
    'This wealth-attracting combo pairs a Pyrite, Citrine, Quartz, Green Aventurine, and Tiger Eye bracel...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'This wealth-attracting combo pairs a Pyrite, Citrine, Quartz, Green Aventurine, and Tiger Eye bracelet with a Raw Pyrite Anklet to invite money and confidence together. It helps you feel grounded, focused, and ready to grow. Key Benefits: • Attracts Wealth - Pyrite and Citrine together support money flow and career growth • Boosts Confidence - Tiger Eye strengthens your belief in yourself and your decisions • Amplifies Energy - Quartz multiplies the power of every crystal in this combo • Brings Luck - Green Aventurine opens doors to new opportunities and positive shifts Lightweight and elegant on the wrist and ankle, this combo also makes a meaningful gift for someone ready to grow.',
    50
  );
INSERT INTO  products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Karungali Malai Silver Capped  6mm – 54+1 Beads (Govt. Certified)',
    'karungali-malai-silver-capped-6mm-54-1-beads-govt-certified',
    'Authentic & Energized',
    'Puja Items',
    'Well-being',
    79900,
    95880,
    4.5,
    184,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/1_11_19940cf3-8b42-403e-a8fd-9a46cd8161bb.webp?v=1780318572',
    '["Authentic","Energized"]',
    'This sacred Karungali Mala is made from pure Black Ebony Wood with silver caps on each of the 54+1 b...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'This sacred Karungali Mala is made from pure Black Ebony Wood with silver caps on each of the 54+1 beads. Wearing it daily helps you feel protected, spiritually grounded, and connected to Lord Murugan''s blessings . Key Benefits: Removes Negativity - Karungali wood absorbs negative energy and shields your aura Deepens Meditation - 54+1 bead count supports focused japam and daily chanting Brings Mental Clarity - Silver caps cool the mind and improve concentration Strengthens Faith - Connects you to divine protection and higher spiritual guidance Each mala is crafted with anti-tarnish oxidised silver-plated caps, and also makes it a meaningful gift for any devotee.',
    50
  );
INSERT INTO  products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Grah Shanti Yantra with Black Tourmaline Frame',
    'grah-shanti-yantra-with-black-tourmaline-frame',
    'Authentic & Energized',
    'Puja Items',
    'Well-being',
    99900,
    119880,
    4.9,
    543,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/Artboard_1_4_d1608791-8b80-4714-aec9-07df075c45a3.webp?v=1779858927',
    '["Authentic","Energized"]',
    'Bring peace, protection, and positive energy into your space with the Grah Shanti Yantra Frame with ...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'Bring peace, protection, and positive energy into your space with the Grah Shanti Yantra Frame with Black Tourmaline . Inspired by Vedic Astrology, this sacred yantra features a Mangal Grah (Mars) grid , where every direction adds up to 9 , symbolising strength, stability, and protection. Key Benefits: Mangal Yantra Energy – Helps reduce stress, conflicts, anger, and marriage-related issues while promoting harmony and balance. Sacred Mantras – Engraved with spiritual mantras to attract peaceful, protective vibrations. Black Tourmaline – Absorb negativity, protect from buri nazar, and create a positive atmosphere. Ideal for your living room, home entrance area, or meditation space .',
    50
  );
INSERT INTO  products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Divya Raksha Mala With 5 Mukhi Trishul Pendant',
    'divya-raksha-mala-with-5-mukhi-trishul-pendant',
    'Authentic & Energized',
    'Puja Items',
    'Well-being',
    99900,
    119880,
    4.8,
    290,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/Artboard1_9_1.webp?v=1779425457',
    '["Authentic","Energized"]',
    'This sacred mala combines Karungali wood beads, Rudraksha, and 5 Mukhi Rudraksha with a Trishul pend...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'This sacred mala combines Karungali wood beads, Rudraksha, and 5 Mukhi Rudraksha with a Trishul pendant, inspired by the divine energies of Lord Shiva &amp; Lord Murugan . Key Benefits: • Spiritual Protection - Karungali and Rudraksha together shield from buri nazar and negative energy. • Mental Clarity - The 5 Mukhi Trishul pendant calms the mind and sharpens focus. • Inner Strength - Lord Shiva’s Trishul awakens courage and personal power. • Removes Obstacles - Clears blockages in your path and invites positive energy. Designed for daily wear, it features anti-tarnish oxidised silver plating and a brass Trishul pendant with long-lasting shine and durability.',
    50
  );
INSERT INTO  products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Karungali Murugan Raksha Mala',
    'karungali-murugan-raksha-mala',
    'Authentic & Energized',
    'Puja Items',
    'Well-being',
    99900,
    119880,
    4.5,
    413,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/Gemini_Generated_Image_v3lcuev3lcuev3lc_1.webp?v=1779692958',
    '["Authentic","Energized"]',
    'Karungali Murugan Raksha Mala brings the divine blessings of Lord Murugan with the sacred energy of ...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'Karungali Murugan Raksha Mala brings the divine blessings of Lord Murugan with the sacred energy of Karungali wood. Sacred Elements in This Mala: • 54 Karungali Beads : Help absorb negativity and maintain positive energy throughout the day • Murugan Pendant : Symbolises courage, divine guidance, and victory over obstacles • Large 17 mm Centre Bead – Represents grounding, stability, focus, and a strong spiritual presence. Designed with an oxidised silver-finish brass pendant and silver-plated caps, this mala offers a bold spiritual look and makes a meaningful gift for protection, blessings, and positivity.',
    50
  );
INSERT INTO  products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Metal Dhan Yog Couple Bracelet Combo',
    'metal-dhan-yog-couple-bracelet-combo',
    'Authentic & Energized',
    'Puja Items',
    'Well-being',
    159900,
    191880,
    4.7,
    394,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/Artboard_1_10.webp?v=1779448821',
    '["Authentic","Energized"]',
    'Made for couples working hard to build a better future together, this combo supports money growth, c...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'Made for couples working hard to build a better future together, this combo supports money growth, career progress, confidence, and financial stability. What’s Inside • Metal Dhan Yog Bracelet for Men (Silver) – Made with Pyrite, Citrine, Tiger Eye, Green Aventurine, and Quartz to support wealth attraction, business growth, leadership qualities, and strong decision-making. • Metal Dhan Yog Bracelet for Women – Made with Pyrite, Citrine, Tiger Eye, Green Aventurine, and Quartz to support financial positivity, emotional balance, self-belief, and new opportunities. Crafted with premium anti-tarnish silver plating, this meaningful couple combo also makes a thoughtful gift for weddings, anniversaries, and partners building a stable life together.',
    50
  );
INSERT INTO  products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Dhan Labh Tortoise',
    'dhan-labh-tortoise',
    'Authentic & Energized',
    'Puja Items',
    'Well-being',
    99900,
    119880,
    4.8,
    56,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/Artboard1_9.webp?v=1779101616',
    '["Authentic","Energized"]',
    'In Vastu Shastra , the tortoise symbolises Lord Kurma, representing stability and protection. Crafte...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'In Vastu Shastra , the tortoise symbolises Lord Kurma, representing stability and protection. Crafted with Pyrite for wealth, and Citrine crystals placed on the tortoise’s back represent prosperity, the Dhan Labh Tortoise symbolises abundance, positivity, and financial growth. Vastu Benefits Attracts Wealth - Place it in the North to invite steady income and financial growth. Eases Financial Stress - Brings stability, calm, and reassurance during difficult financial phases. Boosts Business &amp; Career - Supports growth, new opportunities, and professional success. Perfect Vastu Gift - A deeply meaningful gift for new homes, businesses, and prosperity wishes. Ideal for home, office, shop, cash counter &amp; people seeking dhan labh and financial growth.',
    50
  );
INSERT INTO  products (name, slug, subtitle, category, purpose, price, original_price, rating, reviews, img, badges, short_desc, benefits, size, material, use_for, description, stock) VALUES (
    'Khatu Shyam Murti with Dome',
    'khatu-shyam-murti-with-dome',
    'Authentic & Energized',
    'Puja Items',
    'Well-being',
    119900,
    143880,
    4.7,
    477,
    'https://cdn.shopify.com/s/files/1/0878/4907/4985/files/1-2026-05-18T155529.062.webp?v=1779099953',
    '["Authentic","Energized"]',
    'Bring home the divine blessing of Shyam Baba into your home with the Khatu Shyam Murti with Dome - a...',
    '["Brings Positivity","Enhances Well-being","Spiritual Growth"]',
    'Standard',
    'Natural',
    '["Personal Wear","Puja"]',
    'Bring home the divine blessing of Shyam Baba into your home with the Khatu Shyam Murti with Dome - a sacred idol that brings devotion, hope, prosperity and divine protection to your space. Khatu Shyam ji is lovingly called "Hare Ka Sahara" - the one who holds the hand of those who have lost all hope. Key Benefits Divine Protection - Keeps your home and family safe from buri nazar and negative energy. Peace and Positivity - Fills your space with calm and devotion every single day. Hope and New Beginnings - Invites Shyam Baba''s grace during difficult times and struggles. Perfect Gift - A heartfelt gift for housewarming, weddings, and blessings. Ideal for home mandir, office, and car dashboard.',
    50
  );
